// Copies the generated dataset into public/ so the app can fetch it at runtime
// instead of bundling it. data/courses.json is generated by the Python ETL and
// must never be hand-edited (CLAUDE.md "Dev conventions") -- keeping it out of
// the bundle means a re-scrape does not require a rebuild.
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, '../../data/courses.json');
const dest = resolve(here, '../public/courses.json');

if (!existsSync(src)) {
  console.error('Missing ' + src + '\nRun: python parser/build_courses.py');
  process.exit(1);
}
mkdirSync(dirname(dest), { recursive: true });
copyFileSync(src, dest);
console.log('synced courses.json -> public/');
